GET http://localhost:5000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc2MTE2ODMyLCJleHAiOjE2NzYxNTI4MzJ9.YfBMxv0yfgog1xqXr1F8HxrwGLQAb5eZTqFSb9UFVdk

###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "Lisa",
    "password": "12345"
}

###
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
    "username": "Dasha",
    "password": "12345"
}


###
POST http://localhost:5000/collection
Content-Type: application/json

{
    "idUser" : "1",
    "collectionName" : "Sport",
    "theme" : "Books",
    "description" : "Arsenal.",
    "settings" : "11 23 52" 
}


###
GET http://localhost:5000/collection/2