GET http://localhost:5000/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjc2MTE2ODMyLCJleHAiOjE2NzYxNTI4MzJ9.YfBMxv0yfgog1xqXr1F8HxrwGLQAb5eZTqFSb9UFVdk

###
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "username": "Lisa",
    "password": "12345"
}

###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
    "role": "admin",
}

###
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
    "username": "Dasha",
    "password": "12345"
}


###
POST http://localhost:5000/collection
Content-Type: application/json

{
    "idUser" : "1",
    "image": "img",
    "collectionName" : "Sport",
    "theme" : "Books",
    "description" : "MU.",
    "settings" : "11 23 52" 
}


###
GET http://localhost:5000/collection/1

###
DELETE http://localhost:5000/collection/21


###
POST http://localhost:5000/item
Content-Type: application/json

{
    "collectionId": "17",
    "name": "rrr",
    "params": "[{rrr: '210', rrr: 'Red'}]"
}

###
DELETE http://localhost:5000/item/9

###
GET http://localhost:5000/item/all/17

###
GET http://localhost:5000/item/22

###
GET http://localhost:5000/item/favorite/1


###
PATCH http://localhost:5000/item/2
Content-Type: application/json

{
    "name": "Bober",
    "params": "[{b: '1', a: 'r'}]"
}

###
PATCH http://localhost:5000/item/favorite/1
Content-Type: application/json

{
    "favorite": ["Nikita"]
}


// TAG
###
POST http://localhost:5000/tag
Content-Type: application/json

{
    "collectionId": "17",
    "itemId": "2",
    "tags": ["secondary", "firstly", "success"]
}

###
GET http://localhost:5000/tag/item/16

###
GET http://localhost:5000/tag/collection/17

###
GET http://localhost:5000/tag

###
PATCH http://localhost:5000/tag/15
Content-Type: application/json

{
    "tags": ["success"]
}

###
DELETE http://localhost:5000/tag/2


// COMMENT
###
POST http://localhost:5000/comment
Content-Type: application/json

{
    "itemId": "2",
    "username": "Dasha",
    "comment": "Incredible"
}

###
GET http://localhost:5000/comment/1

###
DELETE http://localhost:5000/comment/6


// LIKE
###
POST http://localhost:5000/like
Content-Type: application/json

{
    "userId": "3",
    "itemId": ["25"]
}

###
PATCH  http://localhost:5000/like/1
Content-Type: application/json

{
    "itemId": ["25"]
}